apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: prometheus
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  selector:
    role: grafana