apiVersion: v1
kind: Service
metadata:
  name: nodeExporter-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
      name: http
  selector:
    role: nodeExporter